In [1]:
from google.colab import files
import pandas as pd

df = files.upload()
data = pd.read_csv('cuaca-harian-dki1-bundaranhi.csv')

Saving cuaca-harian-dki1-bundaranhi.csv to cuaca-harian-dki1-bundaranhi.csv

In [2]:
#testing dataset pertama cuaca harian daerah bundaran hi

data.head()

,time,temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),temperature_2m_mean (°C),relative_humidity_2m_mean (%),...,relative_humidity_2m_max (%),relative_humidity_2m_min (%),cloud_cover_max (%),cloud_cover_min (%),wind_gusts_10m_mean (km/h),wind_speed_10m_mean (km/h),wind_gusts_10m_min (km/h),wind_speed_10m_min (km/h),surface_pressure_max (hPa),surface_pressure_min (hPa)
0,2010-01-01,29.4,24.4,4.0,14.0,16.0,246,16.24,26.6,81,...,90,69,100,99,21.0,10.5,11.9,6.9,1009.3,1005.1
1,2010-01-02,30.8,24.0,6.5,4.0,14.7,238,19.80,26.9,82,...,93,69,100,91,16.5,7.7,9.0,4.4,1009.9,1006.0
2,2010-01-03,30.4,24.3,7.6,11.0,12.6,244,17.32,26.7,83,...,91,70,100,81,18.4,9.4,11.9,6.5,1010.5,1006.5
3,2010-01-04,30.3,25.4,0.9,5.0,19.3,239,20.43,27.4,81,...,91,70,100,17,23.8,13.5,14.4,9.6,1009.1,1005.1
4,2010-01-05,29.9,24.8,14.3,7.0,15.9,247,15.86,26.4,83,...,89,72,100,99,21.6,11.1,10.4,7.8,1009.1,1006.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5722 entries, 0 to 5721
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   time                             5722 non-null   object
 1   temperature_2m_max (°C)          5722 non-null   float64
 2   temperature_2m_min (°C)          5722 non-null   float64
 3   precipitation_sum (mm)           5722 non-null   float64
 4   precipitation_hours (h)          5722 non-null   float64
 5   wind_speed_10m_max (km/h)        5722 non-null   float64
 6   wind_direction_10m_dominant (°)  5722 non-null   int64
 7   shortwave_radiation_sum (MJ/m²)  5722 non-null   float64
 8   temperature_2m_mean (°C)         5722 non-null   float64
 9   relative_humidity_2m_mean (%)    5722 non-null   int64
 10  cloud_cover_mean (%)             5722 non-null   int64
 11  surface_pressure_mean (hPa)      5722 non-null   float64
 12  wind_gusts_10m_max (km/h)        5722 non-null   float64
 13  winddirection_10m_dominant (°)   5722 non-null   int64
 14  relative_humidity_2m_max (%)     5722 non-null   int64
 15  relative_humidity_2m_min (%)     5722 non-null   int64
 16  cloud_cover_max (%)              5722 non-null   int64
 17  cloud_cover_min (%)              5722 non-null   int64
 18  wind_gusts_10m_mean (km/h)       5722 non-null   float64
 19  wind_speed_10m_mean (km/h)       5722 non-null   float64
 20  wind_gusts_10m_min (km/h)        5722 non-null   float64
 21  wind_speed_10m_min (km/h)        5722 non-null   float64
 22  surface_pressure_max (hPa)       5722 non-null   float64
 23  surface_pressure_min (hPa)       5722 non-null   float64
dtypes: float64(15), int64(8), object(1)
memory usage: 1.0+ MB

In [4]:
data.describe()

,temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),temperature_2m_mean (°C),relative_humidity_2m_mean (%),cloud_cover_mean (%),...,relative_humidity_2m_max (%),relative_humidity_2m_min (%),cloud_cover_max (%),cloud_cover_min (%),wind_gusts_10m_mean (km/h),wind_speed_10m_mean (km/h),wind_gusts_10m_min (km/h),wind_speed_10m_min (km/h),surface_pressure_max (hPa),surface_pressure_min (hPa)
count,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,...,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000
mean,30.711430,23.788203,6.151905,8.058895,12.249808,177.765467,18.378789,26.769276,81.446173,77.757078,...,94.253408,63.516253,97.029885,43.847606,15.836019,6.329780,6.740178,2.251153,1011.050944,1006.946575
std,1.778246,0.708299,7.545198,5.993021,3.476465,97.833754,3.768286,0.914782,6.717069,22.239053,...,4.016888,11.023477,9.019196,34.566204,4.169631,2.243109,3.169057,1.892872,1.385511,1.365294
min,24.500000,19.800000,0.000000,0.000000,4.400000,0.000000,2.540000,23.800000,51.000000,3.000000,...,65.000000,22.000000,21.000000,0.000000,8.400000,2.600000,0.700000,0.000000,1006.500000,1002.700000
25%,29.500000,23.400000,0.800000,3.000000,9.700000,90.000000,16.502500,26.200000,78.000000,64.000000,...,93.000000,56.000000,99.000000,12.000000,13.000000,4.800000,4.700000,1.000000,1010.100000,1006.000000
50%,30.600000,23.800000,3.600000,7.000000,11.700000,184.000000,18.990000,26.700000,83.000000,85.000000,...,95.000000,65.000000,100.000000,36.000000,14.700000,5.700000,6.100000,1.800000,1011.100000,1007.000000
75%,31.900000,24.200000,9.100000,12.000000,14.400000,263.000000,20.920000,27.400000,86.000000,97.000000,...,97.000000,72.000000,100.000000,79.000000,17.600000,7.300000,7.900000,2.900000,1012.000000,1007.900000
max,37.500000,26.400000,96.700000,24.000000,27.800000,360.000000,27.630000,30.100000,95.000000,100.000000,...,100.000000,91.000000,100.000000,100.000000,41.200000,20.100000,33.500000,16.100000,1015.600000,1011.700000